### ISSUE TITLE
Dart/flutter package out of date?

### ISSUE THREAD

**Issue by msackman** [RainwayApp/bebop#211]
**Describe the bug**
The dart runtime package at https://pub.dev/publishers/rainway.com/packages is old and doesn't match the runtime dart code (or name!) in this repository. Using bebop in dart/flutter is then harder than normal libraries as I end up copying the runtime dart files out of this repo and setting them up as a local library, rather than a normal import.

**Expected behavior**
`flutter pub add bebop_dart` (or `flutter pub add bebop`) (and equiv for dart) should work and provide the current version of the bebop runtime for dart)

**Comment by EnvOut** [comment]
Guys, what the status with Dart? When it will be available??

**Comment by frbrno** [comment]
I had a little heart attack, when i saw the outdated pub.dev package.
There is another way, just add this to your pubspec.yaml:
```
dependencies:
  flutter:
    sdk: flutter
  # ...

  bebop_dart:
    git:
      url: https://github.com/6over3/bebop.git
      path: Runtime/Dart
      ref: v3.2.3 # use same as 'bebopc --version'
```
